image: golang:1.16-stretch

stages:
  - build
  - test

build job:
  stage: build
  script:
    - echo "test stage build CI"

test job:
  stage: test
  script:
    - echo "go test"
    - go test ./test
    - echo "end test"