image: golang:1.16-stretch

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."

greeter-test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests for greeter from homework9"
    - go test ./greeter > reporttt.txt -coverprofile=coverrr.txt
    - go tool cover -html=cover.txt -o coverrr.html
artifacts:
  paths:
    - ./*.txt
    - ./*.html
  expire_in: 1 day